### ISSUE TITLE
Make dataset available on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [aplesner/Breaking-reCAPTCHAv2#1]
Hi @aplesner,

Niels here from the open-source team at Hugging Face. Congrats on your work, found it from AK's daily papers: https://huggingface.co/papers/2409.08831 (feel free to claim it with your HF account if you have one). I work together with [AK](https://x.com/_akhaliq) on improving the visibility of researchers' work  on the hub.

It'd be great to make the dataset available on the 🤗 hub, we can add tags so that people find them when filtering https://huggingface.co/datasets, so that people can do:

```python
from datasets import load_dataset

dataset = load_dataset("your-hf-username-or-organization/breaking-captchav2-dataset")
```

See here for a guide: https://huggingface.co/docs/datasets/image_dataset.

This would make the dataset easier accessible, and also discoverable.

We can then also link the dataset to the paper page.

Let us know if you need any help.

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by aplesner** [comment]
Here you go: https://huggingface.co/datasets/aplesner-eth/reCAPTCHAv2 

Since the images are more general than just for this paper then I made the name reCAPTCHAv2

**Comment by NielsRogge** [comment]
Thanks a lot!
