### ISSUE TITLE
Can you provide an alternative to Tensorflow_macos

### ISSUE THREAD

**Issue by abishpius** [aplesner/Breaking-reCAPTCHAv2#4]
Aside from being the worst operating system in existence...
Can default tensorflow install be used to replace this dependency?

**Comment by umaiskhan42** [comment]
@abishpius 
Use this code modified by me, also you can use simple tensorflow instead of tensorflow_macos

https://github.com/umaiskhan42/Breaking-reCAPTCHAv2_v2

**Comment by aplesner** [comment]
Updated the requirements
